# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: blist
version: '0.0.0'
github: "wafelj/blist"
license: MIT
author: "Florjan Bartol"
maintainer: "Florjan Bartol"
# synopsis: A new Haskeleton package.
description: blist is my implementation of dlist. It's called blist to avoid conflicts with the dlist package.
# category: Other

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

library:
  dependencies:
  - base
  source-dirs: library

executables:
  blist:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - base
    - blist
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

benchmarks:
  blist-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - base
    - blist
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

tests:
  blist-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - blist
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
