name:                ch24
version:             0.1.0.0
github:              "wafelj/ch24"
license:             BSD3
author:              "Florjan Bartol"
maintainer:          "florjan.bartol@gmail.com"
copyright:           "2018 Florjan Bartol"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/wafelj/ch24#readme>

dependencies:
- base >= 4.7 && < 5
- trifecta >= 1.5.2
- time
- raw-strings-qq >= 1.1
- parsers >= 0.12.9
- containers
- QuickCheck

library:
  source-dirs: src

executables:
  ch24-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch24

tests:
  ch24-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch24
