# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: simple-queue
version: '0.0.0'
github: "wafelj/simple-queue"
license: MIT
author: "Florjan Bartol"
maintainer: "Florjan Bartol"
# synopsis: A new Haskeleton package.
# description: simple-queue is a new Haskeleton package.
# category: Other

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

library:
  dependencies:
  - base
  - deepseq
  source-dirs: library

benchmarks:
  simple-queue-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - base
    - simple-queue
    - criterion
    - containers
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

tests:
  simple-queue-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - simple-queue
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
